name: update hermeto lockfiles

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  update-hermeto-lockfiles:
    runs-on: ubuntu-latest
    container: quay.io/coreos-assembler/fcos-buildroot:testing-devel
    # TODO matrix for every branch
    steps:
      - name: Install dependencies
        run: dnf install -y node python3 python3-pip python3-dnf rpm-ostree
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: jbtrystram/fedora-coreos-config
          ref: hermetic-podman-rawhide
      - name: Generate rpm-lockfile input file
        run: |
          # python is not happy importing a module without the py extension
          cp build-rootfs .github/scripts/container_native.py
          python .github/scripts/generate_rpm_lockfile_config --repo fedora-coreos-pool.repo $(pwd)/manifest.yaml
      - name: Fix /usr/share paths
        # workaround for https://github.com/konflux-ci/rpm-lockfile-prototype/issues/102
        run: sed -i '/makedumpfile/c\- makedumpfile' rpm.in.yaml
      - name: install rpm-lockfile-prototype
        run: |
           python3 -m pip install https://github.com/konflux-ci/rpm-lockfile-prototype/archive/refs/heads/main.zip
      - name: generate lockfile
        run: rpm-lockfile-prototype rpm.in.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update hermeto lockfiles with the latest content from fedora-coreos-pool"
          title: "Bump hermeto lockfiles"
          add-paths: rpms.lock.yaml
          body: |
            This is an auto-generated PR with the results of rpm-lockfile-prototype.
            Source : <link to GH workflow file>
          branch: "bump-lockfiles"
          delete-branch: true
